# Generated by Django 5.2.1 on 2025-06-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ingredientName', models.CharField(max_length=50)),
                ('measure', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Have',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cuisineName', models.CharField(max_length=50)),
                ('categoryName', models.CharField(max_length=20)),
                ('recipeName', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('serving', models.IntegerField()),
                ('description', models.TextField()),
                ('procedure', models.TextField()),
                ('img_url', models.URLField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('ingredients', models.ManyToManyField(through='recipes.Have', to='recipes.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='have',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='have',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
